version: '2'

services:

  elasticsearch:
    image: elasticsearch:5.0
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:5.0
    command: logstash -f /etc/logstash/conf.d/springboot.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./tests_logs:/data/logs
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:5.0
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
